import enum


class Key(enum.Enum):
    ZERO = '0'
    ONE = '1'
    TWO = '2'
    THREE = '3'
    FOUR = '4'
    FIVE = '5'
    SIX = '6'
    SEVEN = '7'
    EIGHT = '8'
    NINE = '9'

    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'
    F = 'F'
    G = 'G'
    H = 'H'
    I = 'I'
    J = 'J'
    K = 'K'
    L = 'L'
    M = 'M'
    N = 'N'
    O = 'O'
    P = 'P'
    Q = 'Q'
    R = 'R'
    S = 'S'
    T = 'T'
    U = 'U'
    V = 'V'
    W = 'W'
    X = 'X'
    Y = 'Y'
    Z = 'Z'

    UP = '↑'
    DOWN = '↓'
    LEFT = '←'
    RIGHT = '→'

    LEFT_ALT = 'LeftAlt'
    LEFT_CTRL = 'LeftCtrl'
    LEFT_SHIFT = 'LeftShift'

    RIGHT_ALT = 'RightAlt'
    RIGHT_CTRL = 'RightCtrl'
    RIGHT_SHIFT = 'RightShift'

    LEFT_BRACKET = '['
    LEFT_PARENTHESIS = '('

    RIGHT_BRACKET = ']'
    RIGHT_PARENTHESIS = ')'

    F1 = 'F1'
    F2 = 'F2'
    F3 = 'F3'
    F4 = 'F4'
    F5 = 'F5'
    F6 = 'F6'
    F7 = 'F7'
    F8 = 'F8'
    F9 = 'F9'
    F10 = 'F10'
    F11 = 'F11'
    F12 = 'F12'

    NUMPAD_ZERO = 'NumPad 0'
    NUMPAD_ONE = 'NumPad 1'
    NUMPAD_TWO = 'NumPad 2'
    NUMPAD_THREE = 'NumPad 3'
    NUMPAD_FOUR = 'NumPad 4'
    NUMPAD_FIVE = 'NumPad 5'
    NUMPAD_SIX = 'NumPad 6'
    NUMPAD_SEVEN = 'NumPad 7'
    NUMPAD_EIGHT = 'NumPad 8'
    NUMPAD_NINE = 'NumPad 9'

    NUMPAD_DIVIDE = 'NumPad /'
    NUMPAD_ENTER = 'NumPad Enter'
    NUMPAD_EQUALS = 'NumPad ='
    NUMPAD_SUBTRACT = 'NumPad -'
    NUMPAD_MULTIPLY = 'NumPad *'
    NUMPAD_PERIOD = 'NumPad .'
    NUMPAD_PLUS = 'NumPad +'

    AMPERSAND = '&'
    ASTERISK = '*'
    AT = '@'

    BACKQUOTE = '`'
    BACKSLASH = '\\'
    BACKSPACE = 'Backspace'
    BREAK = 'Break'

    CAPSLOCK = 'CapsLock'
    CARET = '^'
    CLEAR = 'Clear'
    COLON = ':'
    COMMA = ','

    DELETE = 'Del'
    DOLLAR = '$'

    END = 'End'
    ENTER = 'Enter'
    EQUALS = '='
    ESCAPE = 'Esc'
    EXCLAIM = '!'

    GREATER = '>'

    HASH = '#'
    HELP = 'Help'
    HOME = 'Home'

    INSERT = 'Ins'

    LESS = '<'

    MENU = 'Menu'
    MINUS = '-'

    NUMLOCK = 'NumLock'

    PAGEDOWN = 'PageDown'
    PAGEUP = 'PageUp'
    PAUSE = 'Pause'
    PERIOD = '.'
    PLUS = '+'
    PRINT = 'Print'

    QUESTION = '?'
    QUOTE = '\''
    QUOTE_DOUBLE = '"'

    SCROLLOCK = 'ScrollLock'
    SEMICOLON = ';'
    SLASH = '/'
    SPACE = 'Space'

    TAB = 'Tab'

    UNDERSCORE = '_'
